name: AutoDeploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: if exists CREATE TABLE MIGRATIONS, exec them
    #   if: contains(github.ref_name, 'CreateMigration')
    #   run: php artisan migrate

    - name: git checkout
      uses: actions/checkout@v3

    - name: cache vendor
      id: cache
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # - name: if exists DELETE TABLE MIGRATIONS, exec them
    #   if: contains(github.ref_name, 'DeleteMigration')
    #   run: php artisan migrate

    - name: complete date
      run: date
